name: Build Kamerafyr's Docker image

on:
    push:
        branches: ["main"]

jobs:
    build-docker:
        name: "Build the Docker image"
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/alejoheu/kamerafyr-server:latest
                  platforms: linux/amd64
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
            